let listaDestino = [
    { id:1, nombre: "buenos aires", precio: 30},
    { id:2, nombre: "jujuy", precio: 20},
    { id:3, nombre: "salta", precio: 10},
    { id:4, nombre: "tucuman", precio: 10},
    { id:5, nombre: "santiago del estero", precio: 10},
    { id:6, nombre: "la rioja", precio: 10},
    { id:7, nombre: "mendoza", precio: 15},
    { id:8, nombre: "san juan", precio: 10},
    { id:9, nombre: "chubut", precio: 20},
    { id:10, nombre: "tierra del fuego", precio: 20},
    { id:11, nombre: "catamarca", precio: 10},
    { id:12, nombre: "chaco", precio: 10},
    { id:13, nombre: "formosa", precio: 10},
    { id:14, nombre: "misiones", precio: 10},
    { id:15, nombre: "corrientes", precio: 10},
    { id:16, nombre: "santa fe", precio: 10},
    { id:17, nombre: "entre rios", precio: 10},
    { id:18, nombre: "cordoba", precio: 10},
    { id:19, nombre: "san luis", precio: 15},
    { id:20, nombre: "neuquen", precio: 15},
    { id:21, nombre: "rio negro", precio: 15},
    { id:22, nombre: "la pampa", precio: 10},
    { id:23, nombre: "santa cruz", precio: 20},
  
]